name: grin-disk

services:
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /data/db
    networks:
      - grin-disk-network
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - grin-disk-network
    ports:
      - 7474:7474
    depends_on:
      - database
  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - grin-disk-network
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mongo_data: {}
networks:
  grin-disk-network:
    driver: bridge